#============================================
# Title:  harper-composers.yaml
# Author: James Harper
# Date:   26 August 2023
# Description: YAML file OpenAPI Specification for creating a product catalog
#===========================================

#OAS document format
#version
openapi: "3.0.0"
#general information
info:
  title: Composer API
  version: "1.0"
#paths property
paths:
#List of catalog items
  /composers:
    get:
      tags:
        - Composers
      description: API for obtaining a list of composers from MongoDB Atlas
      summary: returns a list of composer documents. HTTP response 200 is "OK"
      responses:
        "200":
          description: Composer Documents
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
    post:
      tags:
        - Composers
      description: API for adding new composer objects
      summary: Creates a new composer object and adds it to the database
      requestBody:
        description: Composer's information
        content:
          application/json:
            schema:
              required:
                - firstName
                - lastName
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        "200":
          description: User added
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
  /composers/{id}:
    get:
      tags:
        - Composers
      description: API for returning a single composer object by id, from MongoDB
      summary: returns a composer document based on the unique id
      parameters:
        - name: id
          in: path
          required: true
          description: the composerId requested by the user
          schema:
            type: string
      responses:
        "200":
          description: Composer document in JSON format
        "500":
          description: Server Exception
        "501":
          description: MongoDB Exception
